### ISSUE TITLE
PlaceholderAPI support to the reward system

### ISSUE THREAD

**Issue by pjindras** [GeorgeV220/VoteRewards#126]
**Describe the bug**
Voterewards voteparty placeholders in config file in bc command arent working.
Other placeholders (essentials etc. ) are working well.

**Comment by GeorgeV220** [comment]
I didn't understand exactly, where placeholders don't work?

**Comment by pjindras** [comment]
in congig.yml

Services: # By service name (you can disable it if you use per world rewards)
    # default is used if a service name is not listed here. If default is missing, no service will be selected.
    default:
      commands:
        - 'eco give %player% 100'
        - 'crates key give %player% hlasovaci 1'
        - 'broadcast &b%player% &fPrávě hlasoval přes &b/vote a získal odměnu. Do vote párty zbývá %voterewards_voteparty_votes_until% hlasů.

%voterewards_voteparty_votes_until% placeholder or his alternatives aren't working.

**Comment by GeorgeV220** [comment]
Please check the latest release
the placeholderapi placeholders need to be inside a bracket like {voterewards_voteparty_votes_until}
