### ISSUE TITLE
[BUG] Plugin does not load on server startup, but can be manually loaded in.

### ISSUE THREAD

**Issue by UPSOKen** [GeorgeV220/VoteRewards#131]
**Describe the bug**
Whenever the server starts, it says Voterewards loads, but it appears as red in the /pl list. However, If I manually use pluginmanager to load the plugin, it loads into the server just fine, and appears green in /pl until next restart.

**To Reproduce**
Start the server.

**Expected behavior**
Should start at startup.

**Screenshots**
N/A

**Server Information (please complete the following information):**
- Server version (`/bukkit:version`): Pufferfish 1.20.1
- Installed plugins (`/bukkit:plugins`): AntiNetherRoof, ArmedArmorStands, AuxProtect, BuycraftX, ChatFilter, Citizens, CommandPrompter, CoreProtect, CustomDeathMessages, DeathChest
DeluxeCommands, DeluxeMenus, Denizen, Depenizen, Essentials, EssentialsChat, EssentialsDiscord, FarmLimiter, FastAsyncWorldEdit, FreedomChat
GriefPrevention, InsaneAnnouncer, LuckPerms, MiniMOTD, Multiverse-Core, Pl-Hide-Pro, PlaceholderAPI, PlayerParticles, PluginManager, ProtocolLib
SeeMore, Sentinel, spark, squaremap, squaremap-deathspot, squaremap-essentialsx, squaremap-griefprevention, squaremap-mobs, squaremap-vanish, squaremap-worldguard
squaremarker, TAB, TabTPS, TCPShield, Themis, TradeAudit, TradeSystem, UnexpectedSpawn, Vault, ViaBackwards
ViaVersion, VoteRewards, VotifierPlus, WorldGuard, XenoWorldReset
- WorldGuard Report Pastebin Link (`/wg report -p`):  https://paste.enginehub.org/gteG8t6oj.report

**Additional context**
N/A

**Comment by GeorgeV220** [comment]
Do you have any errors in the Console when the plugin tries to load up ?

**Comment by UPSOKen** [comment]
I didn't receive any errors upon loading it. That's why it's confusing me, and it works absolutely fine once I manually load it in.

https://pastebin.com/xDjYpUUH

**Comment by UPSOKen** [comment]
> Do you have any errors in the Console when the plugin tries to load up ?

I finally got an error log on startup:

`[02:30:52] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/VoteRewards.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Votifier]. Please download and install these plugins to run 'VoteRewards'.
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:508) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at java.lang.Thread.run(Unknown Source) ~[?:?]`
	
I use VotifierPlus [https://www.spigotmc.org/resources/votifierplus.74040/] - which works fine once I manually load the plugin, but VoteRewards doesn't like it.

**Comment by GeorgeV220** [comment]
Do you have (Nu)Votifier installed ?

**Comment by UPSOKen** [comment]
> installed ?

No, I use the fork that I linked called VotifierPlus.

It should function exactly the same. In fact, it does - once I manually load the plug-in, but for some reason it won't load on startup.

This seems like something simple, like maybe a dependency list.

**Comment by GeorgeV220** [comment]
ahh, I need to add support for the plugin. I will update it.

**Comment by GeorgeV220** [comment]
Can I send you a test jar ? @UPSOKen

**Comment by UPSOKen** [comment]
> Can I send you a test jar ? @UPSOKen 

Sure! At work currently - but will test later tonight.

**Comment by GeorgeV220** [comment]
[VoteRewards-8.3.0.zip](https://github.com/GeorgeV220/VoteRewards/files/12896974/VoteRewards-8.3.0.zip)

**Comment by UPSOKen** [comment]
> [VoteRewards-8.3.0.zip](https://github.com/GeorgeV220/VoteRewards/files/12896974/VoteRewards-8.3.0.zip)

This appears to work fine for me! I ran it on a clone test server, and it worked. Going to add it to my production server, it restarts tomorrow at 2 am, so if I run into any issues, I will let you know.

Should I close this issue?

**Comment by GeorgeV220** [comment]
> > [VoteRewards-8.3.0.zip](https://github.com/GeorgeV220/VoteRewards/files/12896974/VoteRewards-8.3.0.zip)
> 
> This appears to work fine for me! I ran it on a clone test server, and it worked. Going to add it to my production server, it restarts tomorrow at 2 am, so if I run into any issues, I will let you know.
> 
> Should I close this issue?

Happy to hear that. I will close this issue when we are sure that everything is working and after I release a fix release

**Comment by GeorgeV220** [comment]
> > [VoteRewards-8.3.0.zip](https://github.com/GeorgeV220/VoteRewards/files/12896974/VoteRewards-8.3.0.zip)
> 
> This appears to work fine for me! I ran it on a clone test server, and it worked. Going to add it to my production server, it restarts tomorrow at 2 am, so if I run into any issues, I will let you know.
> 
> Should I close this issue?

Can you verify that the plugin works ?

**Comment by UPSOKen** [comment]
Still working fine for me @GeorgeV220 !
