### ISSUE TITLE
Console error in 1.20.2

### ISSUE THREAD

**Issue by Darkmager** [GeorgeV220/VoteRewards#132]
whenever a player joins it starts throwing error in console
Using in Purpur 1.20.2 Latest Build

https://paste.gg/p/anonymous/fb6d6c7e48b640c893ba2e11b19831c8

**Comment by GeorgeV220** [comment]
Hello, you can ignore it for now. I will push a new update soon.

**Comment by GeorgeV220** [comment]
Hello, fixed in the latest release. Please check it out!!
